version: "3"

volumes:
  mongo_data:

networks:
  postgres-net:
  dev-net:
    driver: bridge

services:
  db:
    image: postgres
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-net
      - dev-net
    volumes:
      - ./tmp/db:/var/lib/postgresql/data